[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
    from = "/"
    to = "https://www.notion.so/nicholasmaurer/Nicholas-Maurer-53e850dbbea741649af7e63e158ec3cf"